#This script takes in a list of slide names, reads the data generated by Miriam segmentation,
#processes it to insert both regional and global coordinates, and does some light filtering
#of cells that are too small or large
#The output is an rds and/or csv file of all cells in the submited slides
#Created by Eliot McKinley (etmckinley@gmail.com)
# Thu Oct 27 10:21:13 2022 ------------------------------

library(tidyverse)
library(exifr)
library(glue)
library(furrr)


slides=read_csv("/Volumes/CellDive/scan_alpha/st_slides_13Jun23.csv")

slides=slides[1,]

#the directory where your data is stored
base_dir = "/Volumes/CellDive/scan_alpha/"

#correct for if there are parentheses in the file name
base_detect=str_replace(base_dir, "\\(", "\\\\(")
base_detect=str_replace(base_detect, "\\)", "\\\\)")

#Get slide and tile size information
image_size=read_exif(list.files(paste0(base_dir, slides$slide_id,"/DAPI Tiles"), pattern =".tif", full.names = TRUE))
region_information = image_size %>%
  select(FileName, Directory, ImageWidth, ImageHeight) %>%
  mutate(region= str_remove(FileName, "S002_mono_dapi_reg_"),
         region= str_remove(region, ".tif"),
         region= str_split_fixed(region, "_r", 2)[,1],
         SlideID=str_remove(Directory, base_detect),
         SlideID=str_remove(SlideID, "/DAPI Tiles")) %>%
  select(region, SlideID, ImageWidth, ImageHeight) %>%
  unique()

#concatenate all
MxIF.cell.filter <- function(
    data, MinCellSize=150, MaxCellSize=2000, MinNucSize=30,
    MaxNucSize=1000, MinMemSize=20, MinCytSize=0, MinNucRatio=0.05
){
  data=subset(data, Cell_Area > MinCellSize)
  data=subset(data, Cell_Area < MaxCellSize)
  data=subset(data, Nuc_Area > MinNucSize)
  data=subset(data, Nuc_Area < MaxNucSize)
  data=subset(data, Mem_Area > MinMemSize)
  data=subset(data, Cyt_Area > MinCytSize)
  data=subset(data, Nuc_Area/Cell_Area > MinNucRatio)
  
  return(data)
}

all=NULL
for (i in 1:nrow(slides)){
  print(slides$slide_id[i])
  positions=dir(paste0(base_dir, slides$slide_id[i], "/SegQuant/PosStats" ), full.names = T)
  #positions=positions[str_detect(positions, "/PosStats/StrPosStats_region", negate=TRUE)]
  if (length(positions)==0){
    next
  }
  
  epi.pos= positions[str_detect(positions, "/PosStats/PosStats_region_", negate=FALSE)]
  str.pos= positions[str_detect(positions, "/PosStats/StrPosStats_region_", negate=FALSE)]
  
  
  epi = epi.pos %>% 
    future_map_dfr(read_csv, show_col_types = FALSE) %>% 
    mutate(epi=1,
           SlideID=slides$slide_id[i]) %>% 
    MxIF.cell.filter() 
  
  
  
  str = str.pos %>% 
    future_map_dfr(read_csv, show_col_types = FALSE) %>% 
    filter(Cell_Area>150 & Cell_Area<3500) %>%
    mutate(epi=0,
           SlideID=slides$slide_id[i])
  
  
  all=bind_rows(all, bind_rows(epi, str)%>% 
                  mutate(region=str_split_fixed(Pos, "_r",2)[,1]))
  
}

all=all |> left_join(region_information) %>% 
  mutate(row=str_split_fixed(Pos, "_[:alpha:]_",3)[,2],
         column=str_split_fixed(Pos, "_[:alpha:]_",3)[,3]) %>% 
  select(ID, SlideID, Pos, row, column, epi, everything() ) |> 
  mutate(row=as.numeric(row),
         column=as.numeric(column))

saveRDS(all, "quantification in progress.rds")

#get positions in region and slide
image_size=read_exif(list.files(paste0(base_dir, slides$slide_id,"/RegisteredImages/S002/"), pattern =".tif", full.names = TRUE))

base_detect=str_replace(base_dir, "\\(", "\\\\(")
base_detect=str_replace(base_detect, "\\)", "\\\\)")

non_tile_information=image_size %>% 
  filter(str_detect( FileName, pattern = "dapi")) %>% 
  mutate(ncol=ceiling(ImageWidth/2048),
         nrow=ceiling(ImageHeight/2048),
         y_size=ceiling(ImageWidth/ncol),
         x_size=ceiling(ImageHeight/nrow)) %>% 
  select(FileName, Directory, ImageWidth, ImageHeight, y_size, x_size, ncol, nrow) %>%
  mutate(region= str_remove(FileName, "S002_mono_dapi_reg_pyr16_"),
         region= str_remove(region, ".tif"),
         #region= str_split_fixed(region, "_r", 2)[,1],
         SlideID=str_remove(Directory, base_detect),
         SlideID=str_remove(SlideID, "/RegisteredImages/S002")) %>%
  select(region, SlideID, y_size, x_size, ncol, nrow, totalWidth=ImageWidth, totalHeight=ImageHeight) %>%
  mutate(AR=totalWidth/totalHeight) %>% 
  unique()
write_csv(non_tile_information, "non_tile_information.csv")

region_information=region_information %>% left_join(non_tile_information)

all=all %>% left_join(non_tile_information)

#get region coordinates
all=all %>% 
  group_by(SlideID, region) %>% 
  #mutate(x = round(Cell_Centroid_X + (as.numeric(column) -1)*ImageHeight - ImageHeight*.1*(as.numeric(column) -1)*.9),
  #       y = round(Cell_Centroid_Y + (as.numeric(row) -1)*ImageWidth - ImageWidth*.1*(as.numeric(row) -1)*.9))
  #mutate(x_correct = round(Cell_Centroid_X + (as.numeric(column) -1)*ImageWidth - (ImageWidth - x_size)*(as.numeric(column) -1)),
  #     y_correct = round(Cell_Centroid_Y + (as.numeric(row) -1)*ImageHeight - (ImageHeight - y_size)*(as.numeric(row) -1)))
  mutate(x=if_else(column < ncol, Cell_Centroid_X + x_size*(column-1), Cell_Centroid_X + x_size*(column-1)- x_size*.1 ),
         y=if_else(row < nrow,  Cell_Centroid_Y + y_size*(row-1), Cell_Centroid_Y + y_size * (row-1) - y_size*.1),
         filter= case_when(column < ncol & Cell_Centroid_X > x_size~1,
                           column == ncol & Cell_Centroid_X < ImageWidth - x_size ~ 1,
                           row < nrow & Cell_Centroid_Y > y_size~1,
                           row == nrow & Cell_Centroid_Y < ImageHeight - x_size ~ 1,
                           TRUE~0)) %>% 
  filter(filter == 0) %>% 
  ungroup() %>% 
  select(-filter, -ImageWidth, -ImageHeight, -y_size, -x_size, -ncol, -nrow, -totalWidth, -totalHeight, -AR)

#get global coordinates
#you may have to change the path here if the first round is different
region_information = region_information %>% 
  mutate(canvas_location = glue("{base_dir}{SlideID}/S001_DAPI_dapi_MUC2_fitc_COLLAGEN_cy3_CD45_cy5/canvas_xform.tsv"))

tform=region_information %>% 
  select(SlideID, canvas_location) %>% 
  unique()

tform_canvas=bind_cols(region_information,
                       read_tsv(tform$canvas_location) %>% select(-region)) %>% 
  mutate(determinant = (a*d - b*c)) %>% 
  mutate(x_mm_min = ((d * (0 - du)) - (c * (0 - dv)))*determinant,
         y_mm_min = ((a * (0 - dv)) - (b * (0 - du)))*determinant,
         x_mm_max = ((d * (width - du)) - (c * (height - dv)))*determinant,
         y_mm_max = ((a * (height - dv)) - (b * (width - du)))*determinant) %>% 
  group_by(SlideID) %>% 
  mutate(x_mm_min_cor = x_mm_min - min(x_mm_min),
         y_mm_min_cor = y_mm_min - min(y_mm_min),
         x_mm_max_cor = max(x_mm_max) - x_mm_max,
         y_mm_max_cor = max(y_mm_max) - y_mm_max)

all=all %>% 
  left_join(tform_canvas %>% select(region, SlideID, a, b, c, d, du, dv, determinant)) %>% 
  mutate(xmdu = x - du,
         ymdv = y - dv,
         x_mm = ((d * xmdu) - (c*ymdv))/determinant,
         y_mm = ((a * ymdv) - (b*xmdu))/determinant) %>% 
  select(everything(), -a, -b,-c,-d,-du, -dv, -determinant, -xmdu, -ymdv)

#change the names

saveRDS(all, "quantification_global_13Jun23.rds")
write_csv(all, "quantification_global_13Jun23.csv")

for (i in 1:length(slides$slide_id)) {
  print(slides$slide_id[i])
  write_csv(
    all %>% filter(all$SlideID==slides$slide_id[i]),
    paste0(slides$slide_id[i], "_threshold_quantificaion.csv")
  )
}

all |> 
  ggplot(aes(x=x_mm, y=y_mm))+
  geom_point()#aes(color=Pos))
